[2023-11-24 10:10:24,630] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-24 10:10:24,635] logger_util.py->write_log line:61 [INFO] 接口名称：获取通道下所有变量信息
[2023-11-24 10:10:24,635] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-24 10:10:24,635] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/tunnel/2/tag/query
[2023-11-24 10:10:24,635] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'cade0634c4a44304911e8cfdb1b8f8b9'}
[2023-11-24 10:10:24,635] logger_util.py->write_log line:61 [INFO] 请求参数：{'groupId': None, 'dataTypes': [], 'usedType': 0, 'keyword': ''}
[2023-11-24 10:10:24,636] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-24 10:10:24,641] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 238, in analysis_yaml
    extract_data = {key: value_list[value2]}
TypeError: 'bool' object is not subscriptable

[2023-11-24 10:10:24,794] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-11-24 10:10:24,795] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


[2023-11-24 10:10:24,838] logger_util.py->error_log line:65 [INFO] 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

[2023-11-24 10:10:24,839] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "E:\Project_python\api_cms\common\requests_util.py", line 335, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 309, in send_request
    self.base_url = self.replace_load(self.base_url) + self.replace_load(url)
  File "E:\Project_python\api_cms\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "E:\Project_python\api_cms\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "E:\Project_python\api_cms\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable


