[2023-05-23 11:38:36,169] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2023-05-23 11:38:36,169] logger_util.py->write_log line:61 [INFO] 接口名称：通过聚合表获取归档表字段配置
[2023-05-23 11:38:36,169] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2023-05-23 11:38:36,169] logger_util.py->write_log line:61 [INFO] 接口路径：http://192.168.4.12:18000/api/v1/dataconfig/filingtable/fields/be59259f-1e43-4308-93fa-0caca8b4afbf
[2023-05-23 11:38:36,169] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2023-05-23 11:38:36,170] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-05-23 11:38:36,517] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 226, in analysis_yaml
    extract_data = {key: return_data[value]}
KeyError: 'id.0'

