[2023-11-27 16:43:44,310] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,310] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-11-27 16:43:44,310] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-27 16:43:44,310] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/test
[2023-11-27 16:43:44,311] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,311] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql3742', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-11-27 16:43:44,311] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,317] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-27 16:43:44,317] logger_util.py->write_log line:61 [INFO] 实际结果：测试连接成功
[2023-11-27 16:43:44,317] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-27 16:43:44,318] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 接口名称：测试连接互联项
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': 'mysql4231', 'connectionType': 1, 'databaseType': 1, 'authenticationType': None, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123', 'changedPassword': True, 'mqttType': None, 'pushType': None, 'timingPeriod': None, 'changingPeriod': None, 'cloudDeviceId': '', 'originalSecret': ''}
[2023-11-27 16:43:44,334] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,355] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-27 16:43:44,355] logger_util.py->write_log line:61 [INFO] 实际结果：{'data': {'id': 19, 'name': 'mysql4231', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': 3306, 'database': 'TestDB', 'databasePath': '', 'userName': 'root'}, 'message': ''}
[2023-11-27 16:43:44,355] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-27 16:43:44,355] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 接口名称：关闭互联项
[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/19/off
[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,365] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,373] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-27 16:43:44,373] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '266df173-fc7a-4654-bd51-2a24b8fcf1b3', 'id': 19, 'type': 1, 'name': 'mysql4231', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-11-27 16:43:44,373] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-27 16:43:44,373] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-27 16:43:44,378] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,379] logger_util.py->write_log line:61 [INFO] 接口名称：开启互联项
[2023-11-27 16:43:44,379] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-27 16:43:44,379] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/switch/1/19/on
[2023-11-27 16:43:44,379] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,379] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,387] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-27 16:43:44,387] logger_util.py->write_log line:61 [INFO] 实际结果：[{'nodeGuid': '8a1eee7c-fad0-47e2-bc5b-b2624a5dc0f9', 'id': 19, 'type': 1, 'name': 'mysql4231', 'status': 0, 'errorMsg': None, 'children': []}]
[2023-11-27 16:43:44,387] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-27 16:43:44,388] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 接口名称：重命名互联项
[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/rename/1/19/重命名_mysql540
[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,393] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,416] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2023-11-27 16:43:44,416] logger_util.py->write_log line:61 [INFO] 实际结果：
[2023-11-27 16:43:44,416] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2023-11-27 16:43:44,416] logger_util.py->write_log line:61 [INFO] 
-------------接口请求结束-----------

[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 
-------------接口请求开始-----------
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 接口名称：修改互联配置
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/connection/19/config
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 请求头：{'X-Project': 'd800d1a6d0be4623aaa824c28dc71981'}
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': '19', 'name': '改配_mysql45', 'connectionType': 1, 'databaseType': 1, 'authenticationType': 0, 'server': '127.0.0.1', 'port': '3306', 'database': 'TestDB', 'databasePath': '', 'userName': 'root', 'password': 'syc123'}
[2023-11-27 16:43:44,432] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2023-11-27 16:43:44,439] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2023-11-27 16:43:44,439] logger_util.py->write_log line:61 [INFO] 实际结果：互联名称已存在, 请重新输入
[2023-11-27 16:43:44,439] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2023-11-27 16:43:44,439] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2023-11-27 16:43:44,440] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2023-11-27 16:43:44,440] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 265, in analysis_yaml
    self.validate_result(yq_result, return_text, status_code)
  File "E:\Project_python\api_cms\common\requests_util.py", line 448, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\api_cms\common\requests_util.py", line 368, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\api_cms\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


