[2022-09-25 15:46:32,975] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:32,976] logger_util.py->write_log line:61 [INFO] 接口名称：新建工程
[2022-09-25 15:46:32,976] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:32,976] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2022-09-25 15:46:32,976] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:32,976] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '工程3282', 'path': 'E:\\APP\\CMS201', 'type': 1, 'parentId': 0}
[2022-09-25 15:46:32,977] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:34,405] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:34,405] logger_util.py->write_log line:61 [INFO] 实际结果：888
[2022-09-25 15:46:34,405] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:34,405] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 接口名称：新建文件夹
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '文件夹3350', 'path': None, 'type': 0, 'parentId': 0}
[2022-09-25 15:46:34,410] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:34,446] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:34,446] logger_util.py->write_log line:61 [INFO] 实际结果：889
[2022-09-25 15:46:34,446] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:34,446] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:34,452] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:34,452] logger_util.py->write_log line:61 [INFO] 接口名称：复制工程
[2022-09-25 15:46:34,452] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:34,453] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node?copyId=888
[2022-09-25 15:46:34,453] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:34,453] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '复制工程3170', 'path': 'E:\\APP\\CMS201', 'type': 1, 'parentId': 0}
[2022-09-25 15:46:34,453] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:35,160] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:35,160] logger_util.py->write_log line:61 [INFO] 实际结果：890
[2022-09-25 15:46:35,160] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:35,160] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:35,164] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:35,164] logger_util.py->write_log line:61 [INFO] 接口名称：删除工程
[2022-09-25 15:46:35,164] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:35,164] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node?isDeleteFile=false
[2022-09-25 15:46:35,164] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2022-09-25 15:46:35,165] logger_util.py->write_log line:61 [INFO] 请求参数：[888]
[2022-09-25 15:46:35,165] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 接口名称：删除文件
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node?isDeleteFile=false
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 请求参数：[889]
[2022-09-25 15:46:35,214] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:35,239] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:35,239] logger_util.py->write_log line:61 [INFO] 接口名称：新建工程
[2022-09-25 15:46:35,240] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:35,240] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2022-09-25 15:46:35,240] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:35,240] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '工程1566', 'path': 'E:\\APP\\CMS201', 'type': 1, 'parentId': 0}
[2022-09-25 15:46:35,240] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,203] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,203] logger_util.py->write_log line:61 [INFO] 实际结果：891
[2022-09-25 15:46:36,204] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,204] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,209] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,209] logger_util.py->write_log line:61 [INFO] 接口名称：新建文件夹
[2022-09-25 15:46:36,209] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,210] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node
[2022-09-25 15:46:36,210] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:36,210] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '文件夹8357', 'path': None, 'type': 0, 'parentId': 0}
[2022-09-25 15:46:36,210] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,244] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,244] logger_util.py->write_log line:61 [INFO] 实际结果：892
[2022-09-25 15:46:36,244] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,244] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] 接口名称：移动文件
[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] 接口方式：put
[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/node/891
[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] 请求头：{}
[2022-09-25 15:46:36,249] logger_util.py->write_log line:61 [INFO] 请求参数：{'child': [], 'id': 891, 'parentId': 892, 'name': '移动工程9784', 'path': 'E:\\APP\\CMS201\\移动工程9784', 'type': 1}
[2022-09-25 15:46:36,250] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,280] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,280] logger_util.py->write_log line:61 [INFO] 接口名称：获取工程信息
[2022-09-25 15:46:36,280] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2022-09-25 15:46:36,280] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/project/891/info
[2022-09-25 15:46:36,281] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8'}
[2022-09-25 15:46:36,281] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,461] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,461] logger_util.py->write_log line:61 [INFO] 实际结果：{'id': 891, 'name': '工程1566', 'identifier': 'b48156753f404b409c13a5745b31f33a', 'path': 'E:\\APP\\CMS201\\工程1566', 'updateTime': '2022-09-25T15:46:36.1855805'}
[2022-09-25 15:46:36,461] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,461] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,467] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,467] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备
[2022-09-25 15:46:36,468] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,468] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,468] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,468] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备9384', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '1', 'Port': '502', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,468] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,553] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,554] logger_util.py->write_log line:61 [INFO] 实际结果：3e330c33-3f23-4e49-b25c-1ce2f2150a62
[2022-09-25 15:46:36,554] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,554] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,561] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,561] logger_util.py->write_log line:61 [INFO] 接口名称：删除设备
[2022-09-25 15:46:36,562] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:36,562] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/3e330c33-3f23-4e49-b25c-1ce2f2150a62
[2022-09-25 15:46:36,562] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,562] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,664] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,664] logger_util.py->write_log line:61 [INFO] 实际结果：
[2022-09-25 15:46:36,664] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,664] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备2133', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '1', 'Port': '502', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,670] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,761] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,761] logger_util.py->write_log line:61 [INFO] 实际结果：a8867a19-4af6-4d9e-b90f-479fc6d33420
[2022-09-25 15:46:36,761] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,761] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,766] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,766] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备_报错提示
[2022-09-25 15:46:36,766] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,766] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,767] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,767] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': ' ', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '1', 'Port': '502', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,767] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,770] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '设备名称不能为空'}]
[2022-09-25 15:46:36,770] logger_util.py->write_log line:61 [INFO] 实际结果：设备名称不能为空
[2022-09-25 15:46:36,771] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,771] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备_报错提示
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备11', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '', 'DeviceID': '1', 'Port': '502', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,777] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,783] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '设备IP不能为空'}]
[2022-09-25 15:46:36,783] logger_util.py->write_log line:61 [INFO] 实际结果：设备IP不能为空
[2022-09-25 15:46:36,783] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,783] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备_报错提示
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备22', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '', 'Port': '502', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,791] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,799] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '设备ID不能为空'}]
[2022-09-25 15:46:36,799] logger_util.py->write_log line:61 [INFO] 实际结果：设备ID不能为空
[2022-09-25 15:46:36,799] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,799] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,804] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备_报错提示
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备33', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '1', 'Port': '', 'TimeOut': '1000', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,805] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,810] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '端口号不能为空'}]
[2022-09-25 15:46:36,810] logger_util.py->write_log line:61 [INFO] 实际结果：端口号不能为空
[2022-09-25 15:46:36,811] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,811] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备_报错提示
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 请求参数：{'id': None, 'name': '设备44', 'description': '描述1', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'parameters': {'ServerName': '127.0.0.1', 'DeviceID': '1', 'Port': '502', 'TimeOut': '', 'ByteOrder': '2143', 'StrByteOrder': '2143'}}
[2022-09-25 15:46:36,816] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,820] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '超时时间不能为空'}]
[2022-09-25 15:46:36,820] logger_util.py->write_log line:61 [INFO] 实际结果：超时时间不能为空
[2022-09-25 15:46:36,820] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,821] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,826] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,826] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备组
[2022-09-25 15:46:36,827] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:36,827] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group
[2022-09-25 15:46:36,827] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,827] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '设备组6676'}
[2022-09-25 15:46:36,827] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:36,928] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:36,929] logger_util.py->write_log line:61 [INFO] 实际结果：52bbbe8e-85ce-455a-aa04-2c15350bdde5
[2022-09-25 15:46:36,929] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:36,929] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:36,935] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:36,936] logger_util.py->write_log line:61 [INFO] 接口名称：删除设备组
[2022-09-25 15:46:36,936] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:36,936] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/52bbbe8e-85ce-455a-aa04-2c15350bdde5
[2022-09-25 15:46:36,936] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:36,936] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,029] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:37,029] logger_util.py->write_log line:61 [INFO] 实际结果：
[2022-09-25 15:46:37,029] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:37,029] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 接口名称：新建设备组
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '设备组6042'}
[2022-09-25 15:46:37,036] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,137] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:37,137] logger_util.py->write_log line:61 [INFO] 实际结果：35730c35-3d59-4714-95b9-dcc40c86b86f
[2022-09-25 15:46:37,137] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:37,137] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] 接口名称：获取设备树
[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/tree
[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,144] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,150] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:37,150] logger_util.py->write_log line:61 [INFO] 实际结果：[{'deviceId': 'a8867a19-4af6-4d9e-b90f-479fc6d33420', 'name': '设备2133', 'protocolType': 1, 'suppiler': '通用', 'model': '通用', 'sort': 0, 'childs': [{'groupId': '35730c35-3d59-4714-95b9-dcc40c86b86f', 'name': '设备组6042', 'sort': 0}]}]
[2022-09-25 15:46:37,150] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:37,151] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,155] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A1', 'type': 3, 'description': '缩:1,小数位:空，舍位', 'address': '400001', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,156] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,161] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,161] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,161] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,162] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,162] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,260] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,260] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,260] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,260] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,261] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,261] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A2', 'type': 3, 'description': '缩:1,小数位:0，四舍', 'address': '400002', 'stringLength': None, 'zoom': 1, 'digit': 0, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,261] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,265] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,265] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,265] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,265] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,266] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A3', 'type': 3, 'description': '缩:1,小数位:2，进位', 'address': '400003', 'stringLength': None, 'zoom': 1, 'digit': 2, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,295] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,301] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,301] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,301] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,301] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,301] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A4', 'type': 3, 'description': '缩:0.001,小数位:空,进位', 'address': '400004', 'stringLength': None, 'zoom': 0.001, 'digit': None, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,328] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,333] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,333] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,333] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,333] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,334] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A5', 'type': 3, 'description': '缩:0.001,小数位:0,舍位', 'address': '400005', 'stringLength': None, 'zoom': 0.001, 'digit': 0, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,361] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,369] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,369] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,369] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,369] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,370] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A6', 'type': 3, 'description': '缩:0.001,小数位:2,四舍', 'address': '400006', 'stringLength': None, 'zoom': 0.001, 'digit': 2, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,401] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,406] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,406] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,406] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,406] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,407] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,436] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,436] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,436] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,436] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,436] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,437] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A7', 'type': 3, 'description': '缩:10,小数位:空,四舍', 'address': '400007', 'stringLength': None, 'zoom': 10, 'digit': None, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,437] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,445] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,445] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,445] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,446] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,446] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,476] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A8', 'type': 3, 'description': '缩:10,小数位:0,进位', 'address': '400008', 'stringLength': None, 'zoom': 10, 'digit': 0, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,477] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,481] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,482] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,482] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,482] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,482] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A9', 'type': 3, 'description': '缩:10,小数位:2,舍位', 'address': '400009', 'stringLength': None, 'zoom': 10, 'digit': 2, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,511] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,515] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,516] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,516] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,516] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,516] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,543] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,543] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,543] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,543] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,544] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,544] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B1', 'type': 3, 'description': '缩:1,小数位:空，舍位', 'address': '400001', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,544] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,548] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,548] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,548] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,549] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,549] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,577] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,577] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,578] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,578] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,578] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,578] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B2', 'type': 3, 'description': '缩:1,小数位:0，四舍', 'address': '400011', 'stringLength': None, 'zoom': 1, 'digit': 0, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,578] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,582] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,582] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,582] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,583] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,583] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B3', 'type': 3, 'description': '缩:1,小数位:2，进位', 'address': '400013', 'stringLength': None, 'zoom': 1, 'digit': 2, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,613] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,618] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,618] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,618] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,619] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,619] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,651] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B4', 'type': 3, 'description': '缩:0.001,小数位:空,进位', 'address': '400015', 'stringLength': None, 'zoom': 0.001, 'digit': None, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,652] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,657] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,657] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,657] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,657] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,658] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,685] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,685] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,685] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,686] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,686] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,686] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B5', 'type': 3, 'description': '缩:0.001,小数位:0,舍位', 'address': '400017', 'stringLength': None, 'zoom': 0.001, 'digit': 0, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,686] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,691] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,691] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,691] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,691] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,691] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B6', 'type': 3, 'description': '缩:0.001,小数位:2,四舍', 'address': '400019', 'stringLength': None, 'zoom': 0.001, 'digit': 2, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,722] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,727] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,727] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,727] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,727] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,727] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,770] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B7', 'type': 3, 'description': '缩:10,小数位:空,四舍', 'address': '400021', 'stringLength': None, 'zoom': 10, 'digit': None, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,771] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,777] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,778] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,778] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,778] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,778] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,805] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,805] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,805] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,806] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,806] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,806] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B8', 'type': 3, 'description': '缩:10,小数位:0,进位', 'address': '400023', 'stringLength': None, 'zoom': 10, 'digit': 0, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,806] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,810] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,810] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,811] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,811] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,811] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,841] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'B9', 'type': 3, 'description': '缩:10,小数位:2,舍位', 'address': '400023', 'stringLength': None, 'zoom': 10, 'digit': 2, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,842] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,849] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,849] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,849] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,849] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,849] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,877] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,877] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,878] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,878] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,878] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,878] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'G1', 'type': 0, 'description': '二进制', 'address': '400029.0', 'stringLength': None, 'zoom': None, 'digit': None, 'rule': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,878] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,882] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,882] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,882] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,883] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,883] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,912] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,912] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,912] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,912] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,912] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,913] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'H1', 'type': 14, 'description': '字符串', 'address': '400030', 'stringLength': 8, 'zoom': None, 'digit': None, 'rule': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,913] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,917] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,917] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,917] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,918] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,918] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,949] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,949] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,949] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,949] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,950] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,950] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C1', 'type': 1, 'description': '有符号8', 'address': '400034', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,950] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,953] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,953] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,954] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,954] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,954] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C2', 'type': 2, 'description': '无符号8', 'address': '400035', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:37,985] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:37,990] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:37,990] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:37,990] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:37,991] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:37,991] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,019] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,019] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,019] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,019] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:38,020] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,020] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C3', 'type': 4, 'description': '无符号16', 'address': '400036', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,020] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,025] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:38,025] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,025] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,025] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:38,025] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C4', 'type': 5, 'description': '有符号32', 'address': '400037', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,058] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,063] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:38,063] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,063] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,063] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:38,064] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C5', 'type': 6, 'description': '无符号32', 'address': '400039', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,094] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,099] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:38,099] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,099] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,100] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:38,100] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C6', 'type': 7, 'description': '有符号64', 'address': '400041', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,134] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,139] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:38,139] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,140] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,140] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:38,141] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/f38159a7-76a1-41c5-add0-25827ca481e1/group/3174b6ef-dc31-4af8-b0d9-df5d36ccb1a7/tag
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'C7', 'type': 8, 'description': '无符号64', 'address': '400045', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,170] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,176] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:38,176] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,176] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,176] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:38,177] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:38,211] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,211] logger_util.py->write_log line:61 [INFO] 接口名称：获取变量
[2022-09-25 15:46:38,211] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2022-09-25 15:46:38,211] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,211] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,212] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,217] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:38,217] logger_util.py->write_log line:61 [INFO] 实际结果：[]
[2022-09-25 15:46:38,218] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,218] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,225] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,225] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量_必填字段校验
[2022-09-25 15:46:38,225] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,225] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,226] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,226] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': ' ', 'type': 3, 'description': '变量名为空', 'address': '400040', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,226] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,230] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '变量名不可为空'}]
[2022-09-25 15:46:38,231] logger_util.py->write_log line:61 [INFO] 实际结果：变量名不可为空，请重新输入
[2022-09-25 15:46:38,231] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,231] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,239] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,239] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量_必填字段校验
[2022-09-25 15:46:38,240] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,240] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,240] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,240] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A1', 'type': 3, 'description': '变量重复', 'address': '400041', 'stringLength': None, 'zoom': 1, 'digit': 0, 'rule': 2, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,240] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,401] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于400
[2022-09-25 15:46:38,401] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:38,402] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,402] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400

[2022-09-25 15:46:38,402] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400


[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量_必填字段校验
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'pp1', 'type': 3, 'description': '变量地址为空', 'address': ' ', 'stringLength': None, 'zoom': 1, 'digit': 2, 'rule': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,431] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,438] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '变量地址不可为空'}]
[2022-09-25 15:46:38,438] logger_util.py->write_log line:61 [INFO] 实际结果：变量地址不可为空，请重新输入
[2022-09-25 15:46:38,438] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,439] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,449] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,449] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量_必填字段校验
[2022-09-25 15:46:38,449] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,450] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,450] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,450] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'pp2', 'type': 14, 'description': '字符串长度为空', 'address': '400043', 'stringLength': None, 'zoom': None, 'digit': None, 'rule': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,450] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,462] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '字符长度不可为空，请重新输入'}]
[2022-09-25 15:46:38,462] logger_util.py->write_log line:61 [INFO] 实际结果：字符长度不可为空，请重新输入
[2022-09-25 15:46:38,462] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,462] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 接口名称：新建变量
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'dd1', 'type': 1, 'description': '新建变量', 'address': '400001', 'stringLength': None, 'zoom': 1, 'digit': None, 'rule': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,473] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,619] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:38,619] logger_util.py->write_log line:61 [INFO] 实际结果：['7df51b79-8244-4da1-8063-b84ca47be5e0']
[2022-09-25 15:46:38,619] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,619] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] 接口名称：删除变量
[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/device/a8867a19-4af6-4d9e-b90f-479fc6d33420/group/35730c35-3d59-4714-95b9-dcc40c86b86f/tag
[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,629] logger_util.py->write_log line:61 [INFO] 请求参数：['7df51b79-8244-4da1-8063-b84ca47be5e0']
[2022-09-25 15:46:38,630] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,792] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:38,792] logger_util.py->write_log line:61 [INFO] 实际结果：
[2022-09-25 15:46:38,792] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,792] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量组
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json; =UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 请求参数：{'name': '内部变量组6707'}
[2022-09-25 15:46:38,797] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:38,985] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:38,985] logger_util.py->write_log line:61 [INFO] 实际结果：7c4c7238-10c6-48fa-bd1e-7012b02b6152
[2022-09-25 15:46:38,985] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:38,986] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:38,993] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'a1', 'type': 3, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:38,994] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,119] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,119] logger_util.py->write_log line:61 [INFO] 实际结果：['e4671127-1de8-4a13-b35c-f79c395beb56']
[2022-09-25 15:46:39,119] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,119] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,125] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,125] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,126] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,126] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,126] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,126] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'a2', 'type': 3, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '66', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,126] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,212] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,212] logger_util.py->write_log line:61 [INFO] 实际结果：['bfea00e7-ed38-401e-a96b-dfbc283b4cec']
[2022-09-25 15:46:39,212] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,212] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,219] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'a3', 'type': 3, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,220] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,302] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,302] logger_util.py->write_log line:61 [INFO] 实际结果：['4f82521d-f5b8-4cc2-a075-c672c40d8cd1']
[2022-09-25 15:46:39,302] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,302] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'b1', 'type': 9, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,310] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,394] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,394] logger_util.py->write_log line:61 [INFO] 实际结果：['c09e7aae-f709-472c-a9ac-4b52c6b6bef7']
[2022-09-25 15:46:39,394] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,395] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'b2', 'type': 9, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '66.456', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,401] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,495] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,495] logger_util.py->write_log line:61 [INFO] 实际结果：['6e24cb80-6d8c-4cb5-b663-26afd2afee25']
[2022-09-25 15:46:39,495] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,496] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,502] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,502] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,502] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,503] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,503] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,503] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'b3', 'type': 9, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,503] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,585] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,585] logger_util.py->write_log line:61 [INFO] 实际结果：['b2ffb0e9-974f-449e-bb6b-b9e92c10b1d9']
[2022-09-25 15:46:39,585] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,585] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,592] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,592] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,592] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,593] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,593] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,593] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'g1', 'type': 0, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,593] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,660] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,660] logger_util.py->write_log line:61 [INFO] 实际结果：['5fb0b1bd-f607-4e5c-b151-141a1e283217']
[2022-09-25 15:46:39,660] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,661] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'g2', 'type': 0, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '1', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,667] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,743] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,744] logger_util.py->write_log line:61 [INFO] 实际结果：['bbc8777c-9381-4b84-80b9-133890a5eee0']
[2022-09-25 15:46:39,744] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,744] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,752] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,752] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,753] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,753] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,753] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,753] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'g3', 'type': 0, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,753] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:39,828] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:39,828] logger_util.py->write_log line:61 [INFO] 实际结果：['2158dd7f-d57b-4303-85fd-85a036e9cc8b']
[2022-09-25 15:46:39,828] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:39,828] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'h1', 'type': 14, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:39,835] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,001] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,001] logger_util.py->write_log line:61 [INFO] 实际结果：['0243d57a-a31e-44a9-8bbb-7eb589776d65']
[2022-09-25 15:46:40,001] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,001] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,008] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,008] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,008] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,008] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,009] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,009] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'h2', 'type': 14, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '88', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,009] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,134] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,135] logger_util.py->write_log line:61 [INFO] 实际结果：['5e793998-c94f-43f7-b2f7-fc4ce2d52805']
[2022-09-25 15:46:40,135] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,135] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,141] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,141] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,141] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,141] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,142] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,142] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'h3', 'type': 14, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,142] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,236] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,236] logger_util.py->write_log line:61 [INFO] 实际结果：['63a392e2-2d34-45b1-88ea-3c40b770cd13']
[2022-09-25 15:46:40,236] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,236] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,244] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'day1', 'type': 11, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,245] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,335] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,335] logger_util.py->write_log line:61 [INFO] 实际结果：['5bc9c05f-095e-4e51-ac73-3c7e11fa8292']
[2022-09-25 15:46:40,335] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,336] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,342] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,342] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,342] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,343] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,343] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,343] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'day2', 'type': 11, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '2022-10-10', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,343] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,346] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:40,346] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:40,346] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,346] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:40,346] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:40,376] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,376] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,376] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,376] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,376] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,377] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'day3', 'type': 11, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,377] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,477] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,477] logger_util.py->write_log line:61 [INFO] 实际结果：['95273820-e792-47e6-a491-468bcef183b9']
[2022-09-25 15:46:40,477] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,477] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,484] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,484] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,484] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,484] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,485] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,485] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'time1', 'type': 12, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,485] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,577] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,577] logger_util.py->write_log line:61 [INFO] 实际结果：['e73b7086-e220-4adc-a3e9-7b5c74c62929']
[2022-09-25 15:46:40,577] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,577] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,583] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,583] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,583] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,584] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,584] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,584] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'time2', 'type': 11, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '18:50:50', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,584] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,586] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:40,587] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:40,587] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,587] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:40,587] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:40,635] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,635] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,635] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,635] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,635] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,636] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'time3', 'type': 12, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,636] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,719] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,719] logger_util.py->write_log line:61 [INFO] 实际结果：['4d8ed2eb-6614-41f0-aff2-1c3b8fdf7100']
[2022-09-25 15:46:40,719] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,719] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,730] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,730] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,731] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,731] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,731] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,731] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'daytime1', 'type': 13, 'description': '初始类型：a无', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,731] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,819] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,819] logger_util.py->write_log line:61 [INFO] 实际结果：['00e7f24e-7bdd-4e53-9d76-e48fe2d90b2f']
[2022-09-25 15:46:40,819] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,819] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,825] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,825] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,825] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,825] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,826] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,826] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'daytime2', 'type': 11, 'description': '初始类型：设定值', 'stringLength': 0, 'setValue': '2022-10-10 18:50:50', 'initType': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,826] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,828] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于200
[2022-09-25 15:46:40,828] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:40,828] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,829] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

[2022-09-25 15:46:40,829] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于200


[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'daytime3', 'type': 13, 'description': '初始类型：退出值', 'stringLength': 0, 'setValue': None, 'initType': 3, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,860] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:40,968] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:40,968] logger_util.py->write_log line:61 [INFO] 实际结果：['53c844c8-e81c-4676-a3eb-38c7ba107322']
[2022-09-25 15:46:40,968] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:40,969] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:40,975] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c1', 'type': 1, 'description': '有符号8进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:40,976] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,052] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,053] logger_util.py->write_log line:61 [INFO] 实际结果：['a27064c6-5526-4005-8977-dac6e25e433c']
[2022-09-25 15:46:41,053] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,053] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,061] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,061] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,061] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,061] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,062] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,062] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c2', 'type': 2, 'description': '无符号8进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,062] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,144] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,144] logger_util.py->write_log line:61 [INFO] 实际结果：['41d50196-6c92-41ad-93f1-f972d9818b85']
[2022-09-25 15:46:41,144] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,144] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,151] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c3', 'type': 4, 'description': '无符号16进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,152] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,261] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,261] logger_util.py->write_log line:61 [INFO] 实际结果：['4ad039ae-630d-4931-8b06-cc72628ac83e']
[2022-09-25 15:46:41,262] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,262] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,268] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c4', 'type': 5, 'description': '有符号32进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,269] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,361] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,361] logger_util.py->write_log line:61 [INFO] 实际结果：['49dd86b7-efc5-4454-afef-0cad8362dfec']
[2022-09-25 15:46:41,361] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,361] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,368] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c5', 'type': 6, 'description': '无符号32进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,369] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,463] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,464] logger_util.py->write_log line:61 [INFO] 实际结果：['a3c638c0-2cd5-44c6-9830-c549c08cdfec']
[2022-09-25 15:46:41,464] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,464] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,484] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,484] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,485] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,485] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,485] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,485] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c6', 'type': 7, 'description': '有符号64进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,485] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,617] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,617] logger_util.py->write_log line:61 [INFO] 实际结果：['d8029ca5-e844-4b75-a540-b81ec81c91cc']
[2022-09-25 15:46:41,618] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,618] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,624] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,624] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,624] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,625] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,625] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,625] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'c7', 'type': 8, 'description': '无符号64进制', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,625] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,702] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,702] logger_util.py->write_log line:61 [INFO] 实际结果：['d5398cf4-2551-4d20-93c9-141dfcedfea9']
[2022-09-25 15:46:41,702] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,702] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,709] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,710] logger_util.py->write_log line:61 [INFO] 接口名称：获取内部变量
[2022-09-25 15:46:41,710] logger_util.py->write_log line:61 [INFO] 接口方式：get
[2022-09-25 15:46:41,710] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,710] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,710] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,716] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,717] logger_util.py->write_log line:61 [INFO] 实际结果：[{'id': 'e4671127-1de8-4a13-b35c-f79c395beb56', 'name': 'a1', 'description': '初始类型：a无', 'type': 3, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'bfea00e7-ed38-401e-a96b-dfbc283b4cec', 'name': 'a2', 'description': '初始类型：设定值', 'type': 3, 'stringLength': 0, 'initType': 1, 'setValue': 66, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '4f82521d-f5b8-4cc2-a075-c672c40d8cd1', 'name': 'a3', 'description': '初始类型：退出值', 'type': 3, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'c09e7aae-f709-472c-a9ac-4b52c6b6bef7', 'name': 'b1', 'description': '初始类型：a无', 'type': 9, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '6e24cb80-6d8c-4cb5-b663-26afd2afee25', 'name': 'b2', 'description': '初始类型：设定值', 'type': 9, 'stringLength': 0, 'initType': 1, 'setValue': 66.456, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'b2ffb0e9-974f-449e-bb6b-b9e92c10b1d9', 'name': 'b3', 'description': '初始类型：退出值', 'type': 9, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '5fb0b1bd-f607-4e5c-b151-141a1e283217', 'name': 'g1', 'description': '初始类型：a无', 'type': 0, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'bbc8777c-9381-4b84-80b9-133890a5eee0', 'name': 'g2', 'description': '初始类型：设定值', 'type': 0, 'stringLength': 0, 'initType': 1, 'setValue': 1, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '2158dd7f-d57b-4303-85fd-85a036e9cc8b', 'name': 'g3', 'description': '初始类型：退出值', 'type': 0, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '0243d57a-a31e-44a9-8bbb-7eb589776d65', 'name': 'h1', 'description': '初始类型：a无', 'type': 14, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '5e793998-c94f-43f7-b2f7-fc4ce2d52805', 'name': 'h2', 'description': '初始类型：设定值', 'type': 14, 'stringLength': 0, 'initType': 1, 'setValue': 88, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '63a392e2-2d34-45b1-88ea-3c40b770cd13', 'name': 'h3', 'description': '初始类型：退出值', 'type': 14, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '5bc9c05f-095e-4e51-ac73-3c7e11fa8292', 'name': 'day1', 'description': '初始类型：a无', 'type': 11, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '95273820-e792-47e6-a491-468bcef183b9', 'name': 'day3', 'description': '初始类型：退出值', 'type': 11, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'e73b7086-e220-4adc-a3e9-7b5c74c62929', 'name': 'time1', 'description': '初始类型：a无', 'type': 12, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '4d8ed2eb-6614-41f0-aff2-1c3b8fdf7100', 'name': 'time3', 'description': '初始类型：退出值', 'type': 12, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '00e7f24e-7bdd-4e53-9d76-e48fe2d90b2f', 'name': 'daytime1', 'description': '初始类型：a无', 'type': 13, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '53c844c8-e81c-4676-a3eb-38c7ba107322', 'name': 'daytime3', 'description': '初始类型：退出值', 'type': 13, 'stringLength': 0, 'initType': 3, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'a27064c6-5526-4005-8977-dac6e25e433c', 'name': 'c1', 'description': '有符号8进制', 'type': 1, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '41d50196-6c92-41ad-93f1-f972d9818b85', 'name': 'c2', 'description': '无符号8进制', 'type': 2, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '4ad039ae-630d-4931-8b06-cc72628ac83e', 'name': 'c3', 'description': '无符号16进制', 'type': 4, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': '49dd86b7-efc5-4454-afef-0cad8362dfec', 'name': 'c4', 'description': '有符号32进制', 'type': 5, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'a3c638c0-2cd5-44c6-9830-c549c08cdfec', 'name': 'c5', 'description': '无符号32进制', 'type': 6, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'd8029ca5-e844-4b75-a540-b81ec81c91cc', 'name': 'c6', 'description': '有符号64进制', 'type': 7, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}, {'id': 'd5398cf4-2551-4d20-93c9-141dfcedfea9', 'name': 'c7', 'description': '无符号64进制', 'type': 8, 'stringLength': 0, 'initType': 0, 'setValue': None, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,730] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,731] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量
[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,741] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'inner', 'type': 3, 'description': '要删除', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,742] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,835] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,835] logger_util.py->write_log line:61 [INFO] 实际结果：['19a1cd23-1ae1-4020-b363-e02f34e67a5e']
[2022-09-25 15:46:41,836] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,836] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] 接口名称：删除内部变量
[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] 接口方式：delete
[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,844] logger_util.py->write_log line:61 [INFO] 请求参数：['19a1cd23-1ae1-4020-b363-e02f34e67a5e']
[2022-09-25 15:46:41,845] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,929] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-09-25 15:46:41,929] logger_util.py->write_log line:61 [INFO] 实际结果：
[2022-09-25 15:46:41,929] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,929] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,941] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,941] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量_字段校验
[2022-09-25 15:46:41,941] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,942] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,942] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,942] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': ' ', 'type': 3, 'description': '内部变量为空', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,942] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,946] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '变量名不可为空，请重新输入'}]
[2022-09-25 15:46:41,947] logger_util.py->write_log line:61 [INFO] 实际结果：变量名不可为空，请重新输入
[2022-09-25 15:46:41,947] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,947] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,954] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,954] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量_字段校验
[2022-09-25 15:46:41,955] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,955] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,955] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,955] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'a2', 'type': 3, 'description': '内部变量重复', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,955] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:41,962] logger_util.py->write_log line:61 [INFO] 预期结果：[{'equals': {'status_code': 400}}, {'contains': '变量名已存在，请重新输入'}]
[2022-09-25 15:46:41,963] logger_util.py->write_log line:61 [INFO] 实际结果：变量名已存在，请重新输入
[2022-09-25 15:46:41,963] logger_util.py->write_log line:61 [INFO] 接口请求成功！
[2022-09-25 15:46:41,963] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:41,975] logger_util.py->write_log line:61 [INFO] -------------接口请求开始-----------
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 接口名称：新建内部变量_字段校验
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 接口方式：post
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 接口路径：http://127.0.0.1:18000/api/v1/variable/inner/group/7c4c7238-10c6-48fa-bd1e-7012b02b6152/tag
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 请求头：{'Content-Type': 'application/json;charset=UTF-8', 'X-Project': 'b48156753f404b409c13a5745b31f33a'}
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 请求参数：[{'name': 'A2', 'type': 3, 'description': 'io变量重复', 'stringLength': 0, 'setValue': None, 'initType': 0, 'historyArchive': {'triggerType': 0, 'startTime': None, 'interval': 0, 'intervalUnit': 0, 'relateTags': [], 'isRelateSelf': False}}]
[2022-09-25 15:46:41,976] logger_util.py->write_log line:61 [INFO] 文件上传：None
[2022-09-25 15:46:42,084] logger_util.py->error_log line:65 [INFO] 断言失败:status_code不等于400
[2022-09-25 15:46:42,085] logger_util.py->write_log line:61 [INFO] 接口请求失败！
[2022-09-25 15:46:42,085] logger_util.py->write_log line:61 [INFO] -------------接口请求结束-----------

[2022-09-25 15:46:42,085] logger_util.py->error_log line:65 [INFO] 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400

[2022-09-25 15:46:42,085] logger_util.py->error_log line:65 [INFO] 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 260, in analysis_yaml
    self.validate_result(yq_result, return_data, status_code)
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 429, in validate_result
    error_log("断言异常：异常信息: %s" % str(traceback.format_exc()))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言异常：异常信息: Traceback (most recent call last):
  File "E:\Project_python\2TestCMS2.0\common\requests_util.py", line 394, in validate_result
    error_log("断言失败:"+assert_key+"不等于"+str(assert_value))
  File "E:\Project_python\2TestCMS2.0\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 断言失败:status_code不等于400


